-- TABELA COM OS CAMPOS A SEREM MASCARADOS
CREATE TABLE CAMPOS_ANONIMOS (
    TABELA VARCHAR2(30),
    CAMPO VARCHAR2(30),
    TIPO VARCHAR2(30)
);

-- INSERE TODOS OS CAMPOS DA TABELA EMPLOYEES NA TABELA DE CAMPOS MASCARADOS
INSERT INTO CAMPOS_ANONIMOS
SELECT  TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM    USER_TAB_COLUMNS
WHERE   TABLE_NAME = 'EMPLOYEES'
AND 	COLUMN_NAME IN ('LAST_NAME','FIRST_NAME','EMAIL','PHONE_NUMBER');

COMMIT;


-- CRIA A PACKAGE
CREATE OR REPLACE PACKAGE BODY PK_PII AS
/******************
	DATA:06/09/2024
	DESCRICAO: ANONIMIZA DADOS COM BASE EM UMA TABELA DE REFERENCIA
	AUTOR: SEU NOME
********************/

	FUNCTION VALIDA_TABELA (P_TABELA VARCHAR2)
	RETURN NUMBER
	IS
	
		V_RETORNO NUMBER(1) := -1;
	
	BEGIN
		
		SELECT 	COUNT(1) --0, SE NAO EXISTIR, 1 SE EXISTIR
		INTO	V_RETORNO
		FROM 	USER_TABLES
		WHERE 	TABLE_NAME = P_TABELA;
		
		RETURN V_RETORNO;
	
	END VALIDA_TABELA;
	
	----
	PROCEDURE ANONIMIZA (P_TABELA VARCHAR2)
	IS
	
		V_TABELA_EXISTENTE NUMBER(1);
		V_COMANDO	VARCHAR2(256);
	
	BEGIN
	
		-- VERIFICAR SE A TABELA EXISTE
		V_TABELA_EXISTENTE := VALIDA_TABELA(P_TABELA);
		
		IF (V_TABELA_EXISTENTE < 1) THEN
		
			RAISE_APPLICATION_ERROR(-20001,'Tabela '||P_TABELA||' não existe');
		
		END IF;
		
		-- ANONIMIZAR OS DADOS
		FOR REGISTRO IN (SELECT TABELA,
								CAMPO,
								TIPO
						 FROM 	CAMPOS_ANONIMOS
						 WHERE	TABELA = P_TABELA) LOOP
			
			-- CONSTROI UM UPDATE DINAMICAMENTE
			V_COMANDO := 'UPDATE '||REGISTRO.TABELA||' SET '||REGISTRO.CAMPO||' = :1';
			
			EXECUTE IMMEDIATE V_COMANDO USING DBMS_RANDOM.STRING('X',20);
		
		END LOOP;
	
	END ANONIMIZA;	
	
END PK_PII;